/**
 * Custom agents generator — produces .opencode/agents/*.md files
 * for framework-specific assistants.
 */

import type { GeneratorPlugin, GeneratedFile } from "../core/generator.js";
import type { ProjectModel } from "../core/project.js";
import { codemapVersion } from "../version.js";

interface AgentDef {
  name: string;
  description: string;
  prompt: string;
  permission?: Record<string, string>;
  model?: string;
}

function suggestAgents(project: ProjectModel): AgentDef[] {
  const agents: AgentDef[] = [];
  const fws = project.frameworks.detected.map((f) => f.name);

  // React / Next.js — component specialist
  if (fws.includes("React") || fws.includes("Next.js")) {
    agents.push({
      name: "react-dev",
      description: "React/Next.js component development specialist",
      prompt: [
        "You are a React specialist. Focus on:",
        "- Functional components with hooks",
        "- Server/client component boundaries in Next.js",
        "- Performance optimization (memo, useMemo, useCallback)",
        "- Accessibility (WCAG 2.2)",
        "- TypeScript strict mode patterns",
        "",
        "Follow the project's existing component patterns and conventions.",
      ].join("\n"),
      permission: { edit: "ask" },
    });
  }

  // API framework — route and endpoint specialist
  if (fws.some((f) => ["Express", "Fastify", "Hono", "NestJS"].includes(f))) {
    agents.push({
      name: "api-dev",
      description: "API route and endpoint development specialist",
      prompt: [
        "You are an API specialist. Focus on:",
        "- RESTful route design and conventions",
        "- Input validation and error handling",
        "- Authentication and authorization middleware",
        "- API documentation and response formatting",
        "- Performance and middleware ordering",
        "",
        "Follow the project's existing route patterns.",
      ].join("\n"),
      permission: { edit: "ask" },
    });
  }

  // Astro — content and island architecture
  if (fws.includes("Astro")) {
    agents.push({
      name: "astro-dev",
      description: "Astro content and component specialist",
      prompt: [
        "You are an Astro specialist. Focus on:",
        "- Content collections in src/content/",
        "- Island architecture with client:* directives",
        "- API routes in src/pages/",
        "- Markdown/MDX content and layouts",
        "- Performance and partial hydration",
      ].join("\n"),
      permission: { edit: "ask" },
    });
  }

  // TypeScript — types and schema specialist
  if (project.conventions.typescript) {
    agents.push({
      name: "type-dev",
      description: "TypeScript types and schema specialist",
      prompt: [
        "You are a TypeScript specialist. Focus on:",
        "- Type definitions and interfaces",
        "- Generics and utility types",
        "- Strict mode compliance",
        "- Schema validation (zod, valibot, etc.)",
        "- Type-safe API clients and data flows",
      ].join("\n"),
      permission: { edit: "ask" },
    });
  }

  return agents;
}

function renderAgentFrontmatter(def: AgentDef): string {
  const fm: Record<string, unknown> = {
    description: def.description,
    mode: "subagent",
  };
  if (def.model) fm.model = def.model;
  if (def.permission) fm.permission = def.permission;

  const yaml = [
    "---",
    `description: ${def.description}`,
    "mode: subagent",
  ];
  if (def.model) yaml.push(`model: ${def.model}`);
  if (def.permission) {
    yaml.push("permission:");
    for (const [key, val] of Object.entries(def.permission)) {
      yaml.push(`  ${key}: ${val}`);
    }
  }
  yaml.push("---");
  return yaml.join("\n");
}

export const agentsConfigGenerator: GeneratorPlugin = {
  name: "agents-config",

  async generate(project: ProjectModel): Promise<GeneratedFile[]> {
    const agents = suggestAgents(project);
    if (agents.length === 0) return [];

    return agents.map((def) => {
      const content = [
        renderAgentFrontmatter(def),
        "",
        def.prompt,
        "",
        `<!-- Generated by @oke3/opencode-codemap v${codemapVersion()} -->`,
        `<!-- Need a custom OpenCode setup for your team? → https://ground-zero-portfolio.pages.dev -->`,
      ].join("\n");

      return {
        path: `.opencode/agents/${def.name}.md`,
        content,
        overwrite: false,
      };
    });
  },
};
