/**
 * Commands generator — produces .opencode/commands/*.md files
 * from detected package.json scripts and conventions.
 */

import type { GeneratorPlugin, GeneratedFile } from "../core/generator.js";
import type { ProjectModel } from "../core/project.js";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { codemapVersion } from "../version.js";

interface CommandDef {
  name: string;
  description: string;
  template: string;
  agent?: string;
}

function detectScripts(project: ProjectModel): CommandDef[] {
  const cmds: CommandDef[] = [];

  // Try reading package.json scripts
  try {
    const pkg = JSON.parse(readFileSync(join(project.root, "package.json"), "utf-8"));
    const scripts = (pkg.scripts ?? {}) as Record<string, string>;

    const known: Record<string, { description: string; agent?: string }> = {
      dev: { description: "Start the development server" },
      build: { description: "Build the project for production" },
      test: { description: "Run the test suite", agent: "build" },
      lint: { description: "Run the linter" },
      format: { description: "Format code" },
      typecheck: { description: "Run TypeScript type checking" },
      preview: { description: "Preview the production build locally" },
      deploy: { description: "Deploy to production", agent: "build" },
      start: { description: "Start the production server" },
      "test:watch": { description: "Run tests in watch mode" },
      "test:e2e": { description: "Run end-to-end tests", agent: "build" },
      storybook: { description: "Start Storybook" },
      "build-storybook": { description: "Build Storybook for deployment" },
    };

    for (const [name, description] of Object.entries(known)) {
      if (scripts[name]) {
        cmds.push({
          name,
          description: description.description,
          template: `Run \`${scripts[name]}\`. Show output and fix any issues.`,
          agent: description.agent,
        });
      }
    }
  } catch {
    // no package.json — skip
  }

  // Add git commands for any project
  cmds.push({
    name: "commit",
    description: "Stage and commit changes with a conventional commit message",
    template: "Run `git diff --cached` to review staged changes. If none, run `git add -A`. Then create a conventional commit message and run `git commit`.",
  });

  return cmds;
}

function renderCommandFrontmatter(def: CommandDef): string {
  const lines = ["---", `description: ${def.description}`];
  lines.push(`template: ${def.template}`);
  if (def.agent) lines.push(`agent: ${def.agent}`);
  lines.push("---");
  return lines.join("\n");
}

export const commandsGenerator: GeneratorPlugin = {
  name: "commands",

  async generate(project: ProjectModel): Promise<GeneratedFile[]> {
    const cmds = detectScripts(project);
    if (cmds.length === 0) return [];

    return cmds.map((def) => {
      const content = [
        renderCommandFrontmatter(def),
        "",
        `<!-- Generated by @oke3/opencode-codemap v${codemapVersion()} -->`,
        `<!-- Need a custom OpenCode setup for your team? → https://ground-zero-portfolio.pages.dev -->`,
      ].join("\n");

      return {
        path: `.opencode/commands/${def.name}.md`,
        content,
        overwrite: false,
      };
    });
  },
};
