/**
 * Multi-tool config generator — produces config for Cursor, Copilot, Codeium, etc.
 * Reuses ProjectModel data to generate contextual AI coding rules.
 * Does NOT depend on any specific AI tool SDK.
 */

import type { GeneratorPlugin, GeneratedFile } from "../core/generator.js";
import type { ProjectModel } from "../core/project.js";
import { codemapVersion } from "../version.js";

// ── Helpers ──────────────────────────────────────────────

function primaryLanguage(project: ProjectModel): string {
  if (project.langTooling.primary) return project.langTooling.primary;
  const langs = project.fileStructure.languages;
  if (langs[".ts"] || langs[".tsx"]) return "TypeScript";
  if (langs[".js"] || langs[".jsx"]) return "JavaScript";
  if (langs[".py"]) return "Python";
  if (langs[".go"]) return "Go";
  if (langs[".rs"]) return "Rust";
  return "Unknown";
}

function buildSummary(project: ProjectModel): string[] {
  const lines: string[] = [];

  if (project.conventions.testRunner) {
    lines.push(`- Test: \`npm test\` (${project.conventions.testRunner})`);
  }
  if (project.conventions.linter) {
    lines.push(`- Lint: \`npm run lint\` (${project.conventions.linter})`);
  }
  if (project.conventions.formatter) {
    lines.push(`- Format: \`npm run format\` (${project.conventions.formatter})`);
  }
  if (project.conventions.typescript) {
    lines.push("- TypeScript" + (project.conventions.strictMode ? " (strict)" : ""));
  }

  return lines;
}

// ── Cursor rules ─────────────────────────────────────────

function renderCursorRules(project: ProjectModel): string {
  const lang = primaryLanguage(project);
  const fw = project.frameworks.primary;
  const parts: string[] = [];

  parts.push(`You are an AI coding assistant for **${project.name}**.`);
  parts.push("");

  if (fw) {
    parts.push(`This project is built with **${fw}** (${lang}).`);
  } else {
    parts.push(`This project is written in **${lang}**.`);
  }
  parts.push("");

  const summary = buildSummary(project);
  if (summary.length > 0) {
    parts.push("## Project conventions");
    parts.push(...summary);
    parts.push("");
  }

  if (project.fileStructure.entryPoints.length > 0) {
    parts.push("## Entry points");
    parts.push(`- Main: \`${project.fileStructure.entryPoints[0]}\``);
    parts.push("");
  }

  parts.push("## Rules");
  parts.push("- Follow the project's existing code style and conventions.");
  parts.push("- Use the standard tooling for this language/framework.");
  if (project.conventions.testRunner) {
    parts.push("- Ensure all existing tests pass before completing work.");
  }
  parts.push(`- Do not add new dependencies without justification.`);
  parts.push("");

  // Lead gen in comment
  parts.push(`<!-- Generated by @oke3/opencode-codemap v${codemapVersion()} -->`);
  parts.push(`<!-- Need a custom OpenCode setup for your team? → https://ground-zero-portfolio.pages.dev -->`);

  return parts.join("\n");
}

// ── Copilot instructions ─────────────────────────────────

function renderCopilotInstructions(project: ProjectModel): string {
  const lang = primaryLanguage(project);
  const fw = project.frameworks.primary;
  const parts: string[] = [];

  parts.push(`# ${project.name} — Copilot Instructions`);
  parts.push("");
  parts.push(`Language: **${lang}**${fw ? `, Framework: **${fw}**` : ""}`);
  parts.push("");

  const summary = buildSummary(project);
  if (summary.length > 0) {
    parts.push("## Build & Test");
    parts.push(...summary);
    parts.push("");
  }

  if (project.fileStructure.entryPoints.length > 0) {
    parts.push("## Entry points");
    parts.push(`- ${project.fileStructure.entryPoints[0]}`);
    parts.push("");
  }

  parts.push("## Coding conventions");
  if (lang === "TypeScript" || lang === "JavaScript") {
    parts.push("- Use ES modules (`import`/`export`)");
    parts.push("- Use `async/await` over callbacks");
  } else if (lang === "Python") {
    parts.push("- Follow PEP 8");
    parts.push("- Use type hints");
  } else if (lang === "Go") {
    parts.push("- Handle errors explicitly (`if err != nil`)");
    parts.push("- Use goroutines for concurrency");
  } else if (lang === "Rust") {
    parts.push("- Follow borrow checker rules");
    parts.push("- Use `Result<T, E>` for fallible operations");
  }
  parts.push("");

  const dirs = project.fileStructure.directories
    .filter((d) => d.split("/").length <= 2)
    .slice(0, 8);
  if (dirs.length > 0) {
    parts.push("## Project structure");
    parts.push("```");
    parts.push(project.name + "/");
    for (const d of dirs) {
      parts.push(`  ${d}/`);
    }
    parts.push("```");
    parts.push("");
  }

  parts.push(`<!-- Generated by @oke3/opencode-codemap v${codemapVersion()} -->`);
  parts.push(`<!-- Need a custom OpenCode setup for your team? → https://ground-zero-portfolio.pages.dev -->`);

  return parts.join("\n");
}

// ── Generator plugin ─────────────────────────────────────

export const multiToolGenerator: GeneratorPlugin = {
  name: "multi-tool",

  async generate(project: ProjectModel): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];

    // .cursorrules — Cursor AI
    files.push({
      path: ".cursorrules",
      content: renderCursorRules(project),
      overwrite: false,
    });

    // .github/copilot-instructions.md — GitHub Copilot
    files.push({
      path: ".github/copilot-instructions.md",
      content: renderCopilotInstructions(project),
      overwrite: false,
    });

    return files;
  },
};
